name: Release

on:
  # Run when a new tag is pushed
  push:
    tags:
      - 'v*.*.*'

  # Run when manually triggered
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: Build release
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install dependencies
        run: deno cache --lock=lock.json

      - name: Build everything
        run: deno task build --target all

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'push'
        with:
          files: ./dist/*
